<Query Kind="Statements">
  <Output>DataGrids</Output>
</Query>

//How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

List<double> nums = new List<double>();

for (int a = 2; a <= 100; a++)
for (int b = 2; b <= 100; b++)
  nums.Add(Math.Pow(a, b));

nums.Distinct()
    .Count()
    .Dump();
