# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

from sequences import (fibonacci, even)
from itertools import takewhile


def main():
    predicate = lambda x: x < 4000000
    domain = takewhile(predicate, even(fibonacci()))
    return sum(domain)


if (__name__ == "__main__"):
    print main()
