-- Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

-- Triangle	 	    Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
-- Pentagonal	 	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
-- Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
-- It can be verified that T285 = P165 = H143 = 40755.

-- Find the next triangle number that is also pentagonal and hexagonal.

main :: IO ()
main = print $ 
    head [x | x <- hexs, x > 40755, isPent x]

upperBound :: Integer
upperBound = 1000000

-- don't really need this... all triangle numbers are hexagonal
tris :: [Integer]
tris = scanl (+) 1 [2..upperBound]

pents :: [Integer]
pents = scanl (+) 1 [4,7..upperBound]

hexs :: [Integer]
hexs = scanl (+) 1 [5,9..upperBound]

-- pulled from the web... faster way to check for a pent than x `elem` pents
isPent :: Integer -> Bool
isPent n = (af == 0) && ai `mod` 6 == 5
  where (ai, af) = properFraction . sqrt $ 1 + 24 * (fromInteger n)
