-- Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
-- 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
-- It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
-- Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D

import Data.Set


problem_0044 :: Integer
problem_0044 = head [b-a | b <- pentagonalSeries, a <- takeWhile (<b) pentagonalSeries, evaluatePair a b]


pentagonalSeries :: [Integer]
pentagonalSeries = [(n*(3*n-1)) `div` 2 | n <- [1..5000]]


-- original approach used `elem`. Using Data.Set and choosing not to use an infinite pentagonalSeries sped things up
-- isPentagonal :: Integer -> Bool
-- isPentagonal n = n `elem` ps
--     where ps = takeWhile (<=n) pentagonalSeries


isPentagonal :: Integer -> Bool
isPentagonal = (`member` fromList pentagonalSeries)


evaluatePair :: Integer -> Integer -> Bool
evaluatePair pj pk = isPentagonal (pj+pk) && isPentagonal (pk-pj)
